version: "3"
services:
  frontend:
    container_name: frontend_local
    image: frontend_local
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

  backend:
    container_name: backend_local
    image: backend_local
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env