version: "3"
services:
  frontend:
    container_name: frontend_vault
    image: beavervaultadmin/beaver-vault-pm-frontend:master
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env

  backend:
    container_name: backend_vault
    image: beavervaultadmin/beaver-vault-pm-backend:master
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_POLL_INTERVAL=30
        - WATCHTOWER_DISABLE_CONTAINERS="nginx-proxy-manager"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock