export const fakePasswords = [
  {
    id: 1,
    website: "reference.com",
    username: "zbirtonshaw0",
    password: "yO2{*iE?r",
  },
  {
    id: 2,
    website: "devhub.com",
    username: "idavidovics1",
    password: "eD5!0gy)N)BXFhwE",
  },
  {
    id: 3,
    website: "cafepress.com",
    username: "vfordham2",
    password: "rK2)rbI/KD",
  },
  {
    id: 4,
    website: "yellowpages.com",
    username: "boronan3",
    password: 'wT8"m`V*buPVq\\',
  },
  {
    id: 5,
    website: "homestead.com",
    username: "aliversidge4",
    password: "hH1@F$$@",
  },
  {
    id: 6,
    website: "seattletimes.com",
    username: "ccalderon5",
    password: "wF7}y3i%3\\",
  },
  {
    id: 7,
    website: "washingtonpost.com",
    username: "nfrobisher6",
    password: "rE2{yt)U|um~B",
  },
  {
    id: 8,
    website: "princeton.edu",
    username: "hriditch7",
    password: "pW6/E?0APm+",
  },
  {
    id: 9,
    website: "networksolutions.com",
    username: "ssudddard8",
    password: "dU1/yq.`#>Qv|kO",
  },
  {
    id: 10,
    website: "tmall.com",
    username: "qbattye9",
    password: "iG7?xy}D.i?x4K",
  },
  {
    id: 11,
    website: "dagondesign.com",
    username: "bbrainsbya",
    password: "nE5'>%sbxgDmM",
  },
  {
    id: 12,
    website: "moonfruit.com",
    username: "rrustmanb",
    password: "aP6.sM4hft\\n2",
  },
  {
    id: 13,
    website: "bing.com",
    username: "oferrarettoc",
    password: "jJ2|+3i6",
  },
  {
    id: 14,
    website: "amazon.co.uk",
    username: "cwayted",
    password: "dK7,X%W2",
  },
  {
    id: 15,
    website: "youtube.com",
    username: "alampele",
    password: 'fO1"=q0S??',
  },
  {
    id: 16,
    website: "whitehouse.gov",
    username: "coyleyf",
    password: "hO8<qNl0",
  },
  {
    id: 17,
    website: "nydailynews.com",
    username: "bfulkerg",
    password: "zA5}Z`V?6",
  },
  {
    id: 18,
    website: "mayoclinic.com",
    username: "dpapworthh",
    password: "xW0#2'hIviS`L",
  },
  {
    id: 19,
    website: "auda.org.au",
    username: "scasboni",
    password: "nF7'sE?q@.q')u",
  },
  {
    id: 20,
    website: "wikipedia.org",
    username: "tgostlingj",
    password: "lM7`!CDP@|",
  },
  {
    id: 21,
    website: "cnbc.com",
    username: "cbolderstonek",
    password: "cX2/*jIqtq)83$GR",
  },
  {
    id: 22,
    website: "yolasite.com",
    username: "kjakubovitsl",
    password: "iO1!_Ofk@!=",
  },
  {
    id: 23,
    website: "slideshare.net",
    username: "hcundeym",
    password: "hQ6<_..OA\\AJb3i",
  },
  {
    id: 24,
    website: "cnn.com",
    username: "mokeeffen",
    password: "eO7>@hd6h@t<",
  },
  {
    id: 25,
    website: "weebly.com",
    username: "aogdahlo",
    password: "kD8_oy#\\K",
  },
  {
    id: 26,
    website: "wp.com",
    username: "zkittlesp",
    password: "xB4`?%'LP%&fII",
  },
  {
    id: 27,
    website: "trellian.com",
    username: "dblodgettsq",
    password: "fH3*Y3</",
  },
  {
    id: 28,
    website: "csmonitor.com",
    username: "gsoarr",
    password: "gP8%aV66N#c)Z>",
  },
  {
    id: 29,
    website: "ycombinator.com",
    username: "ltoozes",
    password: "zA0#<u7v)'I",
  },
  {
    id: 30,
    website: "digg.com",
    username: "mgilsthorpet",
    password: "xE4,8&E!Z",
  },
  {
    id: 31,
    website: "google.ca",
    username: "mdelgardillou",
    password: "sM9,T_bv3",
  },
  {
    id: 32,
    website: "over-blog.com",
    username: "jhastwallv",
    password: "uX7$a4aQf",
  },
  {
    id: 33,
    website: "pbs.org",
    username: "mmulcahyw",
    password: "cS0=PB<`ua9>Z",
  },
  {
    id: 34,
    website: "ted.com",
    username: "csleetx",
    password: "cX5..d|CF#",
  },
  {
    id: 35,
    website: "jimdo.com",
    username: "aboxally",
    password: "tQ9#Lm/M`",
  },
  {
    id: 36,
    website: "elegantthemes.com",
    username: "hfilyukovz",
    password: "yO6/=1_WVfB4?9@",
  },
  {
    id: 37,
    website: "imageshack.us",
    username: "bduckinfield10",
    password: "qS3{RA/Ce",
  },
  {
    id: 38,
    website: "vistaprint.com",
    username: "adagnan11",
    password: "zN4{,E9z$A`",
  },
  {
    id: 39,
    website: "princeton.edu",
    username: "bkleinzweig12",
    password: "zQ2|!7Q+&",
  },
  {
    id: 40,
    website: "fastcompany.com",
    username: "abarreau13",
    password: "lI6|KU=0m}}@h0p",
  },
  {
    id: 41,
    website: "vkontakte.ru",
    username: "ylindsley14",
    password: 'pA7/RkOt1U38d"\\',
  },
  {
    id: 42,
    website: "microsoft.com",
    username: "dvandenbosch15",
    password: "wX9%$Vix",
  },
  {
    id: 43,
    website: "163.com",
    username: "mgyppes16",
    password: "jE2!*Ng#Bs_B~",
  },
  {
    id: 44,
    website: "zdnet.com",
    username: "twhyman17",
    password: "tM1$iRG6m,J}R1AI",
  },
  {
    id: 45,
    website: "sohu.com",
    username: "nberetta18",
    password: "bI9)#dRCbX@e\\b",
  },
  {
    id: 46,
    website: "biglobe.ne.jp",
    username: "rcanada19",
    password: "oL7@2#7!~N",
  },
  {
    id: 47,
    website: "auda.org.au",
    username: "ogenike1a",
    password: "wQ1<B5&yZuYaZ",
  },
  {
    id: 48,
    website: "smh.com.au",
    username: "jfinlry1b",
    password: "oK3={vI/cV`\\R+w",
  },
  {
    id: 49,
    website: "instagram.com",
    username: "nbrogi1c",
    password: "xW8(/SOEMs{7F",
  },
  {
    id: 50,
    website: "marriott.com",
    username: "chupka1d",
    password: "vZ5.IJJqar6?o<",
  },
];
